### ISSUE TITLE
mpc_generator 生成的 mpc 文件

### ISSUE THREAD

**Issue by HopeDevote** [WeBankBlockchain/WeDPR#207]
您好，
      

1. 请问由 `mpc_generator`插件将`SQL`语句转换成`MPC`语言，生成`mpc`文件，WeDPR是如何处理该`mpc`文件的呢？

2. 自定义的WeDPR MPC语法,其相应的源文件位置在哪呢？因为在文档、代码中没有查找到相关信息

**Comment by HaoXuan40404** [comment]
针对第一个问题，WeDPR的算法解析器会讲mpc文件编译成字节码，各方载入相同字节码后执行相同操作
针对第二个问题，目前解析后台还未开源，会在后续计划中推出

**Comment by HopeDevote** [comment]
谢谢您的回答

**Comment by HaoXuan40404** [comment]
> 谢谢您的回答！
> 
> ```
>     那对于WeDPR中的mpc部分，总的来说大概流程是不是：
>      高级程序(自定义的MPC语法) -> 算法解析器(未开源) -> 字节码 -> 后端各方载入字节码执行？
> ```

是的

**Comment by HopeDevote** [comment]
好的，感谢！
